### ISSUE TITLE
compression error with Stage 6 processed data?

### ISSUE THREAD

**Issue by kriemo** [meltonlab/scbeta_indrops#2]
Hi,
  I am trying to regenerate a tSNE projection from your manuscript to examine the expression of a few genes, but am getting an error when trying to decompress or read the Stage 6 count matrices available through GEO. 

Here's code to reproduce the error with the processed count matrix on GEO `GSE114412_Stage_6.all.processed_counts.tsv.gz`

```bash
wget ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE114nnn/GSE114412/suppl/GSE114412%5FStage%5F6%2Eall%2Eprocessed%5Fcounts%2Etsv%2Egz
```

```bash
gunzip GSE114412_Stage_6.all.processed_counts.tsv.gz
gzip: GSE114412_Stage_6.all.processed_counts.tsv.gz: invalid compressed data--format violated
```

Try to read into python:
```python
import pandas as pd
df = pd.read_csv("GSE114412_Stage_6.all.processed_counts.tsv.gz", sep = "\t")
#' Traceback (most recent call last):
#'   File "<stdin>", line 1, in <module>
#'   File "/cluster/software/modules-python/python/3.6.3/lib/python3.6/site-packages/pandas/io/parsers.py", line 705, in parser_f
#'     return _read(filepath_or_buffer, kwds)
#'   File "/cluster/software/modules-python/python/3.6.3/lib/python3.6/site-packages/pandas/io/parsers.py", line 451, in _read
#'  data = parser.read(nrows)
#'   File "/cluster/software/modules-python/python/3.6.3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1065, in read
#'     ret = self._engine.read(nrows)
#'   File "/cluster/software/modules-python/python/3.6.3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1828, in read
#'     data = self._reader.read(nrows)
#'   File "pandas/_libs/parsers.pyx", line 894, in pandas._libs.parsers.TextReader.read
#'   File "pandas/_libs/parsers.pyx", line 916, in pandas._libs.parsers.TextReader._read_low_memory
#'   File "pandas/_libs/parsers.pyx", line 970, in pandas._libs.parsers.TextReader._read_rows
#'   File "pandas/_libs/parsers.pyx", line 957, in pandas._libs.parsers.TextReader._tokenize_rows
#'   File "pandas/_libs/parsers.pyx", line 2189, in pandas._libs.parsers.raise_parser_error
#'   File "/cluster/software/modules-python/python/3.6.3/lib/python3.6/_compression.py", line 68,  in readinto
#'     data = self.read(len(byte_view))
#'   File "/cluster/software/modules-python/python/3.6.3/lib/python3.6/gzip.py", line 471, in read
#'     uncompress = self._decompressor.decompress(buf, size)
#' zlib.error: Error -3 while decompressing data: invalid distance code
```

Try to read into R:
```R
library(readr)
dat <- read_tsv("GSE114412_Stage_6.all.processed_counts.tsv.gz")
#' Error in read_connection_(con) :
#'  Evaluation error: error reading from the connection.
#' In addition: Warning message:
#' In (function (con, what, n = 1L, size = NA_integer_, signed = TRUE,  :
#'   invalid or incomplete compressed data
```

I can read the data from Stage 5 without error, so perhaps there was an issue during transfer to GEO? Any suggestions would be greatly appreciated. Thanks!

**Comment by kriemo** [comment]
FYI, this compression error is fixed in the updated data on GEO.
